apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkg-cluster
  namespace: tkg
spec:
  distribution:
    version: v1.20.7
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: kubernetes 
    workers:
      count: 3
      class: bext best-effort-xsmall
      storageClass: kubernetes 
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["192.168.100.0/24"]
      pods:
        cidrBlocks: ["192.168.0.0/16"]
    storage:
      classes: ["kubernetes"]
      defaultClass: kubernetes 